---
title: "COVID COMBAT study"
subtitle: '[COvid-19 Multi-omics Blood ATlas (COMBAT) Consortium, Cell, 2022](https://doi.org/10.1016/j.cell.2022.01.012)'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: true
---

<!---


cd /sc/arion/projects/CommonMind/hoffman/variancePartition_analysis
ml pandoc 


system("git pull"); rmarkdown::render("COVID_combat_major.Rmd");


system("cp -f COVID_combat_major.html ~/www/")

https://hoffmg01.dmz.hpc.mssm.edu/COVID_combat_major.html


# cd 

--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```


```{r load, cache=FALSE}
library(DESeq2)
library(edgeR)
library(SingleCellExperiment)
library(dreamlet)
library(variancePartition)
library(tidyverse)
library(GenomicDataStream)
library(aplot)
library(kableExtra)
library(parallel)
```

```{r read_data}
# read single cell RNA-seq
file = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/covid19_combat/covid_counts.h5ad"
sce = readH5AD(file)

# use HGNC names
rownames(sce) = rowData(sce)$feature_name

# remove doublets
sce = sce[,sce$GEX_region != "E: Doublets"]

# remove nan cells
sce = sce[,sce$major_subset != "nan"]
```


```{r merge.data}
# read metadata
file = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/covid19_combat/CBD-KEY-CLINVAR/COMBAT_CLINVAR_for_processed.txt"
df = read.table(file, header=TRUE)

# filter and merge metadata
df = df[df$scRNASeq_sample_ID %in% sce$scRNASeq_sample_ID,]
idx = match(sce$scRNASeq_sample_ID, df$scRNASeq_sample_ID)
colData(sce) = cbind(colData(sce), df[idx,])

# For each donor, select the most severe sample
res = colData(sce) %>%
	as_tibble %>%
	select(donor_id, scRNASeq_sample_ID, Source) %>%
	distinct %>%
  group_by(donor_id) %>%
  slice_max(Source)

	# summarize(donor_id, Source, i = which.max(Source),
		# use_sample_id = scRNASeq_sample_ID[which.max(Source)])

# subset to one sample per donor
sceSub = sce[,sce$scRNASeq_sample_ID %in% droplevels(res$scRNASeq_sample_ID)]

# Keep only Oxford samples since Source and Institute are confounded:
# Flu was the only one collected at St_Georges
sceSub = sceSub[,sceSub$Institute == "Oxford"]

# create pseudobulk
pb <- aggregateToPseudoBulk(sceSub,
    assay = "counts",     
    cluster_id = "major_subset",  
    sample_id = "scRNASeq_sample_ID",
    verbose = FALSE)
```


## Properties of dataset
```{r properties}
df = data.frame(table(pb$Source))
colnames(df) = c("Disease status", "Count")

df %>%
  kbl(row.names=FALSE) %>% 
  kable_classic(full_width = FALSE) 

df = list()
df$`# Samples` = ncol(pb)
df$`# Cells` = ncol(sce)
df = unlist(df)
df = data.frame(Property=names(df), count = df)

df %>%  
  kbl(row.names=FALSE) %>% 
  kable_classic(full_width = FALSE) 
```



```{r DESeq2, eval=FALSE}
form <- ~ Age + sex + Source

resList <- mclapply(assayNames(pb), function(CT){

  countMat <- assay(pb, CT)
  keep <- colSums(countMat) > 10000

  dds <- DESeqDataSetFromMatrix(
    countData = countMat[,keep], 
    colData = colData(pb)[keep,],
    design = form)

  # Fit negative binomial models
  dds <- DESeq(dds)

  # Variance partition analysis
  vp <- varpart(dds)

  list( vp = vp, dds = dds)
  }, mc.cores=8)
names(resList) <- assayNames(pb)
```

```{r edgeR}
form <- ~ Age + sex + Source

resList <- mclapply(assayNames(pb), function(CT){

  countMat <- assay(pb, CT)
 
  keep <- colSums(countMat) > 10000

  d <- DGEList(
    counts = countMat[,keep], 
    samples = data.frame(colData(pb))[keep,])
  design <- model.matrix(form, d$samples)
  keep2 <- filterByExpr(d, design, min.count=.1)
  d <- d[keep2,]

  d <- normLibSizes(d)
  design <- model.matrix(form, d$samples)
  d <- estimateDisp(d, design)
  fit <- glmQLFit(d, design)
  fit <- glmQLFTest(fit)

  vp <- varpart(fit, dispObj = d, formula = form)

  list( vp = vp, fit = fit, dispObj = d)
  }, mc.cores=8)
names(resList) <- assayNames(pb)
```




# Plots
```{r plot.vp, fig.height=7, fig.width=12}
figList <- lapply( names(resList), function(CT){

  message(CT)

  if( is(resList[[CT]], "try-error") ) return(NULL)

  vp <- sortCols(resList[[CT]]$vp)
  # dds <- resList[[CT]]$dds
  fit <- resList[[CT]]$fit
  d <- resList[[CT]]$d

  col = c(ggColorHue(ncol(vp) - 2), "grey85", "grey65")

  # Violin plot of variance fractions
  fig1 <- plotVarPart(sortCols(vp), col=col) + 
    theme(aspect.ratio=1,
      plot.title = element_text(hjust = 0.5)) + 
    ggtitle(CT)

  # Count noise vs magnitude
  fig2 <- plotTrendVP( fit, vp, "CountNoise", d )

  # top gene from each column
  i <- apply(vp, 2, which.max)

  # Percent Bars
  fig3 <- plotPercentBars( vp[i,], col=col) +
    theme(aspect.ratio=1)

  genes <- rownames(vp)[i]
  names(genes) <- names(i)

  # log2 CPM
  geneExpr <- edgeR::cpm(d$counts, log = TRUE)

  # Source
  g <-  genes["Source"]
  df <-  data.frame(y = geneExpr[g,], d$samples)
  fig4 <- plotStratify(
    formula = y ~ Source, 
    data = df,
    ylab = bquote(Expression~(log[2]~CPM)), 
    main = g,
    legend=FALSE, 
    x.labels=TRUE) + 
    theme(legend.position = "none",
      axis.text.x = element_text(angle = 0), 
      aspect.ratio=1)

  # Age
  g <- genes["Age"]
  df <-  data.frame(y = geneExpr[g,], d$samples)

  fig5 <- ggplot(df, aes(Age, y)) +
    geom_point() +
    theme_bw() +
    theme(aspect.ratio=1,
      plot.title = element_text(hjust = 0.5)) +
    geom_smooth(method="lm") +
    xlab("Age") +
    ylab(bquote(Expression~(log[2]~CPM))) +
    ggtitle(g)

  # Sex
  g <- genes["sex"]
  df <-  data.frame(y = geneExpr[g,], d$samples)
  fig6 <- plotStratify(
    formula = y ~ sex, 
    data = df,
    ylab = bquote(Expression~(log[2]~CPM)), 
    main = g,
    legend=FALSE, 
    x.labels=TRUE) + 
    theme(legend.position = "none",
      axis.text.x = element_text(angle = 0), 
      aspect.ratio=1)

  fig = (fig1 | fig2 | fig3) / (fig4 | fig5 | fig6)
  fig
  # ggsave(fig, file="~/www/test.pdf", width=12)
})

figList
```









# Session info
<details>
```{r sessionInfo}
sessionInfo()
```
</details>



