---
title: "Multimodally profiling memory T cells from a tuberculosis cohort identifies cell state associations with demographics, environment and disease (GSE158769)"
subtitle: '[Nathan, et al. Nat Immunol  (2021)](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE158769)'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
    toc: true
    smart: false
---


<!---


cd /sc/arion/projects/CommonMind/hoffman/variancePartition_analysis
ml pandoc 

system("git pull"); rmarkdown::render("Nathan_NatImm_2021.Rmd");


system("cp -f Nathan_NatImm_2021.html ~/www/")

https://hoffmg01.dmz.hpc.mssm.edu/Nathan_NatImm_2021.html

--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

Perform dreamlet analysis of single cell data assaying T cell populations in donors infected with tuberculosis.

# Loading
## Load libraries
```{r load.packages, cache=FALSE}
library(SingleCellExperiment)
library(GenomicDataStream)
library(dreamlet)
library(scater)
library(ggplot2)
library(tidyverse)
library(parallel)
library(kableExtra)
library(edgeR)
library(aplot)
library(RColorBrewer)
```

# Load data
```{r load.data}
# read H5AD file
path = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/Nathan_NatImm_2021/"
file = paste0(path, "/Nathan_NatImm_2021.h5ad")
sce = readH5AD(file)   

# get only single-cell RNA-seq
# rest is CITE-seq proteins
only_rna = grep("prot", rownames(sce), invert=TRUE)

# create variable that distinguishes cells from the same donor
# but different batches
# sce$donor_batch = with(colData(sce), paste(donor, batch))
sce$batch = factor(sce$batch)
sce$season = factor(sce$season)
sce$TB_status = factor(sce$TB_status, c("CONTROL", "CASE"))

# sort cell clusters by name
sce = sce[only_rna,sce$cluster_name != "NA"]
colData(sce) = droplevels(colData(sce))
tab = colData(sce) %>%
  as_tibble %>%
  group_by(cluster_ids, cluster_name) %>%
  filter(row_number()==1) %>%
  summarise(cluster_ids, cluster_name) %>%
  arrange(as.numeric(gsub("C-", '', cluster_ids)))

sce$cluster_name = factor(sce$cluster_name, unique(tab$cluster_name))
sce$cluster_ids = factor(sce$cluster_ids, unique(tab$cluster_ids))

# create pseudobulk 
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "cluster_name",  
    sample_id = "donor")
```


```{r edgeR}
form = ~ TB_status + season + sex + age + age^2 + prop_NAT

resList <- mclapply(assayNames(pb), function(CT){

  countMat <- assay(pb, CT)
 
  keep <- colSums(countMat) > 1000

  d <- DGEList(
    counts = countMat[,keep], 
    samples = data.frame(colData(pb))[keep,])
  design <- model.matrix(form, d$samples)
  keep2 <- filterByExpr(d, design)
  d <- d[keep2,]

  d <- normLibSizes(d)
  design <- model.matrix(form, d$samples)
  d <- estimateDisp(d, design)
  fit <- glmQLFit(d, design)
  fit <- glmQLFTest(fit, coef="TB_statusCASE")

  vp <- varpart(fit, dispObj = d, formula = form)

  list( vp = vp, fit = fit, dispObj = d)
  }, mc.cores=8)
names(resList) <- assayNames(pb)
```




# Plots
```{r plot.vp, fig.height=7, fig.width=12}
pal <- brewer.pal(9, "Set1")

figList <- lapply( names(resList), function(CT){

  message(CT)

  if( is(resList[[CT]], "try-error") ) return(NULL)

  vp <- sortCols(resList[[CT]]$vp)
  # dds <- resList[[CT]]$dds
  fit <- resList[[CT]]$fit
  d <- resList[[CT]]$d

  # col <- c(ggColorHue(ncol(vp) - 2), "grey85", "grey65")
  col <- c(pal[seq(1, ncol(vp) - 2)], "grey85", "grey65")

  # Violin plot of variance fractions
  fig1 <- plotVarPart(sortCols(vp), col=col) + 
    theme(aspect.ratio=1,
      plot.title = element_text(hjust = 0.5)) + 
    ggtitle(CT)

  # Count noise vs magnitude
  fig2 <- plotTrendVP( fit, vp, "CountNoise", dispObj = d )

  # top gene from each column
  i <- apply(vp, 2, which.max)

  # Percent Bars
  fig3 <- plotPercentBars( vp[i,], col=col) +
    theme(aspect.ratio=1)

  genes <- rownames(vp)[i]
  names(genes) <- names(i)

  # log2 CPM
  geneExpr <- edgeR::cpm(d$counts, log = TRUE)

  # TB_statusCASE
  g <- genes["TB_status"]
  df <-  data.frame(y = geneExpr[g,], d$samples)
  fig4 <- plotStratify(
    formula = y ~ TB_status, 
    data = df,
    ylab = bquote(Expression~(log[2]~CPM)), 
    main = g,
    legend=FALSE, 
    x.labels=TRUE) + 
    theme(legend.position = "none",
      axis.text.x = element_text(angle = 0), 
      aspect.ratio=1)

  # age
  g <- genes["age"]
  df <-  data.frame(y = geneExpr[g,], d$samples)

  fig5 <- ggplot(df, aes(age, y)) +
    geom_point() +
    theme_bw() +
    theme(aspect.ratio=1,
      plot.title = element_text(hjust = 0.5)) +
    geom_smooth(method="lm") +
    xlab("Age") +
    ylab(bquote(Expression~(log[2]~CPM))) +
    ggtitle(g)

  # Sex
  g <- genes["sex"]
  df <-  data.frame(y = geneExpr[g,], d$samples)
  fig6 <- plotStratify(
    formula = y ~ sex, 
    data = df,
    ylab = bquote(Expression~(log[2]~CPM)), 
    main = g,
    legend=FALSE, 
    x.labels=TRUE) + 
    theme(legend.position = "none",
      axis.text.x = element_text(angle = 0), 
      aspect.ratio=1)

  fig = (fig1 | fig2 | fig3) / (fig4 | fig5 | fig6)
  fig
  # ggsave(fig, file="~/www/test.pdf", width=12)
})

figList
```










