---
title: "Analysis of Alzheimer's Disease in [PsychAD](https://adknowledgeportal.synapse.org/Explore/Projects/DetailsPage?Grant%20Number=R01AG067025)"
subtitle: 'Public Release 0'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
---


<!---


cd /sc/arion/projects/CommonMind/hoffman/variancePartition_analysis
ml pandoc 

system("git pull"); rmarkdown::render("PsychAD_r0_analysis.Rmd");


system("cp -f PsychAD_r0_analysis.html ~/www/")


https://hoffmg01.dmz.hpc.mssm.edu/PsychAD_r0_analysis.html


--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```

# Load libraries
```{r load.packages, cache=FALSE}
suppressPackageStartupMessages({
library(DESeq2)
library(edgeR)
library(SingleCellExperiment)
library(dreamlet)
library(variancePartition)
library(tidyverse)
library(GenomicDataStream)
library(aplot)
library(kableExtra)
library(parallel)
library(RColorBrewer)
source("plotVolcano.R")
})
```


```{r load.data}
file <- "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/FULL_2024-02-01_18_49_PB_SubID_subclass.RDS"

pb <- readRDS( file )

form <- ~ Age + Sex + Brain_bank + Dx + PMI 

pb$Dx <- factor(pb$c11x, c("Control", "AD"), ordered=FALSE)

resList <- mclapply(assayNames(pb), function(CT){

  countMat <- assay(pb, CT)
 
  keep <- (colSums(countMat) > 1000) & !is.na(pb$Dx)

  d <- DGEList(
    counts = countMat[,keep], 
    samples = data.frame(colData(pb))[keep,])
  design <- model.matrix(form, droplevels(d$samples))
  keep2 <- filterByExpr(d, design)
  d <- d[keep2,]

  d <- normLibSizes(d)
  design <- model.matrix(form, droplevels(d$samples))
  d <- estimateDisp(d, design)
  fit <- glmQLFit(d, design)

  vp <- varpart(fit, dispObj = d, formula = form)

  list( vp = vp, fit = fit, dispObj = d)
  }, mc.cores=8)
names(resList) <- assayNames(pb)
```


# Plots
```{r plot.vp, fig.height=7, fig.width=12}
pal <- brewer.pal(9, "Set1")

figList <- lapply( names(resList), function(CT){

  message(CT)

  if( is(resList[[CT]], "try-error") ) return(NULL)

  vp <- sortCols(resList[[CT]]$vp)
  # dds <- resList[[CT]]$dds
  fit <- resList[[CT]]$fit
  d <- resList[[CT]]$d

  # col <- c(ggColorHue(ncol(vp) - 2), "grey85", "grey65")
  col <- c(pal[seq(1, ncol(vp) - 2)], "grey85", "grey65")

  # Violin plot of variance fractions
  fig1 <- plotVarPart(sortCols(vp), col=col) + 
    theme(aspect.ratio=1,
      plot.title = element_text(hjust = 0.5)) + 
    ggtitle(CT)

  # Count noise vs magnitude
  fig2 <- plotTrendVP( fit, vp, "CountNoise", dispObj = d )

  # top gene from each column
  vp_filter = vp[-grep("ENSG", rownames(vp)),]
  i <- apply(vp_filter, 2, which.max)

  genes <- rownames(vp_filter)[i]
  names(genes) <- names(i)

  if( CT == "Micro"){
    genes["Dx"] <- "PTPRG"
  }

  # Percent Bars
  fig3 <- plotPercentBars( vp[genes,], col=col) +
    theme(aspect.ratio=1)

  # log2 CPM
  geneExpr <- edgeR::cpm(d$counts, log = TRUE)

  # AD
  g <- genes["Dx"]
  df <-  data.frame(y = geneExpr[g,], d$samples)
  fig4 <- plotStratify(
    formula = y ~ Dx, 
    data = df,
    ylab = bquote(Expression~(log[2]~CPM)), 
    main = g,
    legend=FALSE, 
    x.labels=TRUE) + 
    theme(legend.position = "none",
      axis.text.x = element_text(angle = 0), 
      aspect.ratio=1)

  # Age
  g <- genes["Age"]
  df <-  data.frame(y = geneExpr[g,], d$samples)
  df <- df[abs(scale(df$y)) < 8,]

  fig5 <- ggplot(df, aes(Age, y)) +
    geom_point() +
    theme_bw() +
    theme(aspect.ratio=1,
      plot.title = element_text(hjust = 0.5)) +
    geom_smooth(method="lm") +
    xlab("Age") +
    ylab(bquote(Expression~(log[2]~CPM))) +
    ggtitle(g)

  # Sex
  # g <- genes["Sex"]
  # df <-  data.frame(y = geneExpr[g,], d$samples)
  # fig6 <- plotStratify(
  #   formula = y ~ Sex, 
  #   data = df,
  #   ylab = bquote(Expression~(log[2]~CPM)), 
  #   main = g,
  #   legend=FALSE, 
  #   x.labels=TRUE) + 
  #   theme(legend.position = "none",
  #     axis.text.x = element_text(angle = 0), 
  #     aspect.ratio=1)

  fit = glmQLFTest(fit, "DxAD")
  tab = topTags(fit, n=Inf)
  tab = data.frame(tab)
  tab$P.Value = tab$PValue

  fig6 = .plotVolcano(tab)

  fig = (fig1 | fig2 | fig3) / (fig6 | fig4 | fig5)
  fig
  # ggsave(fig, file="~/www/test.pdf", width=12)
})

figList
```

## Effective sample size
```{r neff, eval=FALSE}
df <- lapply( names(resList), function(CT){

  message(CT)

  if( is(resList[[CT]], "try-error") ) return(NULL)

  vp <- sortCols(resList[[CT]]$vp)

  tibble(CellType = CT,
    CountNoise = vp$CountNoise)
}) %>%
  bind_rows

fig1 = df %>%
  ggplot(aes(CellType, CountNoise, fill=CellType)) +
    geom_violin() +
    geom_boxplot(width=.1) +
    theme_classic() +
    theme(aspect.ratio=1, legend.position="none") +
    coord_flip() 

fig2 = df %>%
  group_by(CellType) %>%
  summarize(n = n()) %>%
  ggplot(aes(CellType, n, fill=CellType)) +
    geom_col() +
    theme_classic() +
    theme(aspect.ratio=1, legend.position="none") +
    coord_flip() 

fig1 | fig2

```

```{r supp.plot}

library(cowplot)

figList <- lapply( names(resList), function(CT){

  message(CT)

  if( is(resList[[CT]], "try-error") ) return(NULL)

  vp <- sortCols(resList[[CT]]$vp)
  fit <- resList[[CT]]$fit
  d <- resList[[CT]]$d

  # col <- c(ggColorHue(ncol(vp) - 2), "grey85", "grey65")
  col <- c(pal[seq(1, ncol(vp) - 2)], "grey85", "grey65")

  # Violin plot of variance fractions
  fig1 <- plotVarPart(vp, col=col) + 
    theme(aspect.ratio=1,
      plot.title = element_text(hjust = 0.5),
      axis.text.x = element_text(angle = 45, hjust = 1)) +
    ggtitle(CT)

  # Count noise vs magnitude
  fig2 <- plotTrendVP( fit, vp, "CountNoise", dispObj = d )
  list(fig1 = fig1, fig2 = fig2)
})

fig = plot_grid(plotlist = unlist(figList[1:16]), ncol=4)
ggsave(fig, file="Figure_S_PsychAD_1.pdf", height=30, width=12)

fig = plot_grid(plotlist = unlist(figList[17:27]), ncol=4)
ggsave(fig, file="Figure_S_PsychAD_2.pdf", height=22, width=12)
```




# Session Info
<details>
```{r sessioninfo, cache=FALSE}
sessionInfo()
```
</details>






